import 'dart:convert';

class DummyDataHolder {
  static String donatedItems = jsonEncode([
    {
      "donationId": "D001",
      "donorId": "U101",
      "ngoId": null,
      "name": "Men's Winter Jackets",
      "type": "Clothing",
      "description": "Gently used winter jackets suitable for cold weather.",
      "available": true,
      "location": "Addis Ababa",
      "image": "assets/dummy_assets/jacket.jpg",
      "createdAt": "2025-01-05T10:15:30Z",
    },
    {
      "donationId": "D002",
      "donorId": "U102",
      "ngoId": "NGO201",
      "name": "Rice Bags",
      "type": "Food",
      "description": "Five 25kg bags of rice, properly packed.",
      "available": false,
      "location": "Adama",
      "image": "assets/dummy_assets/rice.jpg",
      "createdAt": "2025-01-06T08:40:00Z",
    },
    {
      "donationId": "D003",
      "donorId": "U103",
      "ngoId": null,
      "name": "School Notebooks",
      "type": "Education",
      "description": "New notebooks suitable for primary school students.",
      "available": true,
      "location": "Bahir Dar",
      "image": "assets/dummy_assets/School_Notebooks.jpeg",
      "createdAt": "2025-01-07T12:00:00Z",
    },
    {
      "donationId": "D004",
      "donorId": "U104",
      "ngoId": "NGO202",
      "name": "Used Laptops",
      "type": "Electronics",
      "description": "Two used laptops in working condition.",
      "available": false,
      "location": "Hawassa",
      "image": "assets/dummy_assets/Used_Laptops.jpeg",
      "createdAt": "2025-01-08T14:20:10Z",
    },
    {
      "donationId": "D005",
      "donorId": "U105",
      "ngoId": null,
      "name": "Baby Clothes",
      "type": "Clothing",
      "description": "Clothes for babies aged 0–2 years.",
      "available": true,
      "location": "Dire Dawa",
      "image": "assets/dummy_assets/Baby_Clothes.jpeg",
      "createdAt": "2025-01-09T09:55:45Z",
    },
    {
      "donationId": "D006",
      "donorId": "U106",
      "ngoId": "NGO203",
      "name": "Medical Masks",
      "type": "Health",
      "description": "500 unused medical face masks.",
      "available": false,
      "location": "Mekelle",
      "image": "assets/dummy_assets/Medical_Masks.jpeg",
      "createdAt": "2025-01-10T11:30:00Z",
    },
    {
      "donationId": "D007",
      "donorId": "U107",
      "ngoId": null,
      "name": "Blankets",
      "type": "Relief",
      "description": "Warm blankets suitable for emergency relief.",
      "available": true,
      "location": "Gondar",
      "image": "assets/dummy_assets/Blankets.jpeg",
      "createdAt": "2025-01-11T16:45:20Z",
    },
    {
      "donationId": "D008",
      "donorId": "U108",
      "ngoId": "NGO204",
      "name": "Cooking Utensils",
      "type": "Household",
      "description": "Set of pots and pans in good condition.",
      "available": false,
      "location": "Jimma",
      "image": "assets/dummy_assets/Cooking_Utensils.jpeg",
      "createdAt": "2025-01-12T07:10:00Z",
    },
    {
      "donationId": "D009",
      "donorId": "U109",
      "ngoId": null,
      "name": "Story Books",
      "type": "Education",
      "description": "Children’s story books for ages 6–12.",
      "available": true,
      "location": "Debre Markos",
      "image": "assets/dummy_assets/Story_Books.jpeg",
      "createdAt": "2025-01-13T13:00:00Z",
    },
    {
      "donationId": "D010",
      "donorId": "U110",
      "ngoId": "NGO205",
      "name": "Dry Food Package",
      "type": "Food",
      "description": "Mixed dry food items including pasta and lentils.",
      "available": false,
      "location": "Shashamane",
      "image": "assets/dummy_assets/Dry_Food_Package.jpeg",
      "createdAt": "2025-01-14T18:25:30Z",
    },
  ]);

  static String unavailableItems = jsonEncode([
    {
      "donationId": "D002",
      "donorId": "U102",
      "ngoId": "NGO201",
      "name": "Rice Bags",
      "type": "Food",
      "description": "Five 25kg bags of rice, properly packed.",
      "available": false,
      "location": "Adama",
      "image": "assets/dummy_assets/rice.jpg",
      "createdAt": "2025-01-06T08:40:00Z",
    },
    {
      "donationId": "D004",
      "donorId": "U104",
      "ngoId": "NGO202",
      "name": "Used Laptops",
      "type": "Electronics",
      "description": "Two used laptops in working condition.",
      "available": false,
      "location": "Hawassa",
      "image": "assets/dummy_assets/Used_Laptops.jpeg",
      "createdAt": "2025-01-08T14:20:10Z",
    },
    {
      "donationId": "D006",
      "donorId": "U106",
      "ngoId": "NGO203",
      "name": "Medical Masks",
      "type": "Health",
      "description": "500 unused medical face masks.",
      "available": false,
      "location": "Mekelle",
      "image": "assets/dummy_assets/Medical_Masks.jpeg",
      "createdAt": "2025-01-10T11:30:00Z",
    },
    {
      "donationId": "D008",
      "donorId": "U108",
      "ngoId": "NGO204",
      "name": "Cooking Utensils",
      "type": "Household",
      "description": "Set of pots and pans in good condition.",
      "available": false,
      "location": "Jimma",
      "image": "assets/dummy_assets/Cooking_Utensils.jpeg",
      "createdAt": "2025-01-12T07:10:00Z",
    },
    {
      "donationId": "D010",
      "donorId": "U110",
      "ngoId": "NGO205",
      "name": "Dry Food Package",
      "type": "Food",
      "description": "Mixed dry food items including pasta and lentils.",
      "available": false,
      "location": "Shashamane",
      "image": "assets/dummy_assets/Dry_Food_Package.jpeg",
      "createdAt": "2025-01-14T18:25:30Z",
    },
  ]);

  static String myDonatedItems = jsonEncode([
    {
      "donationId": "D004",
      "donorId": "U104",
      "ngoId": "NGO202",
      "name": "Used Laptops",
      "type": "Electronics",
      "description": "Two used laptops in working condition.",
      "available": false,
      "location": "Hawassa",
      "image": "assets/dummy_assets/Used_Laptops.jpeg",
      "createdAt": "2025-01-08T14:20:10Z",
    },
    {
      "donationId": "D005",
      "donorId": "U105",
      "ngoId": null,
      "name": "Baby Clothes",
      "type": "Clothing",
      "description": "Clothes for babies aged 0–2 years.",
      "available": true,
      "location": "Dire Dawa",
      "image": "assets/dummy_assets/Baby_Clothes.jpeg",
      "createdAt": "2025-01-09T09:55:45Z",
    },
    {
      "donationId": "D006",
      "donorId": "U106",
      "ngoId": "NGO203",
      "name": "Medical Masks",
      "type": "Health",
      "description": "500 unused medical face masks.",
      "available": false,
      "location": "Mekelle",
      "image": "assets/dummy_assets/Medical_Masks.jpeg",
      "createdAt": "2025-01-10T11:30:00Z",
    },
  ]);

  static List<Map<String, dynamic>> donationRequests = [
    {
      "ngoId": "NGO307",
      "itemName": "Children’s Storybooks",
      "type": "Education",
      "quantityRequested": 120,
      "image": "assets/dummy_assets/requests/Children’s Storybooks.jpeg",
      "description": "Books for community libraries and schools.",
      "location": "Jimma",
      "createdAt": "2026-01-21T16:25:00Z",
    },
    {
      "ngoId": "NGO308",
      "itemName": "Lunch for Refugee Children",
      "type": "Food",
      "quantityRequested": 0,
      "image": "assets/dummy_assets/requests/Lunch for Refugee Children.jpeg",
      "description": "Lunch meals for children in refugee camps.",
      "location": "Mekelle",
      "createdAt": "2026-01-21T17:40:00Z",
    },
    {
      "ngoId": "NGO309",
      "itemName": "School Supplies for Refugee Children",
      "type": "stationery",
      "quantityRequested": 200,
      "image": "assets/dummy_assets/requests/school for Refugee Children.jpeg",
      "description": "Stationery items for school children.",
      "location": "Gondar",
      "createdAt": "2026-01-21T18:55:00Z",
    },
    {
      "ngoId": "NGO310",
      "itemName": "fundraising for heart surgery",
      "type": "Health",
      "quantityRequested": 0,
      "image":
          "assets/dummy_assets/requests/fundraising for heart surgery.jpeg",
      "description": "fundraising for heart children surgery.",
      "location": "Dire Dawa",
      "createdAt": "2026-01-21T19:20:00Z",
    },
    {
      "ngoId": "NGO301",
      "itemName": "Winter Boots",
      "type": "Footwear",
      "quantityRequested": 60,
      "image": "assets/dummy_assets/requests/Winter Boots.jpeg",
      "description": "Warm boots for children in cold regions.",
      "location": "Bahir Dar",
      "createdAt": "2026-01-21T10:30:00Z",
    },
    {
      "ngoId": "NGO302",
      "itemName": "LED Lamps",
      "type": "Electronics",
      "quantityRequested": 40,
      "image": "assets/dummy_assets/requests/LED_Lamps.jpeg",
      "description": "Energy-efficient lamps for study centers.",
      "location": "Addis Ababa",
      "createdAt": "2026-01-21T11:15:00Z",
    },
    {
      "ngoId": "NGO303",
      "itemName": "Solar Lanterns",
      "type": "Energy",
      "quantityRequested": 100,
      "image": "assets/dummy_assets/requests/Solar Lanterns.jpeg",
      "description": "Solar lanterns for rural households with no electricity.",
      "location": "Gambela",
      "createdAt": "2026-01-21T12:45:00Z",
    },
    {
      "ngoId": "NGO304",
      "itemName": "Reusable Water Bottles",
      "type": "Health",
      "quantityRequested": 150,
      "image": "assets/dummy_assets/requests/Reusable Water Bottles.jpeg",
      "description": "Reusable bottles for school children.",
      "location": "Dire Dawa",
      "createdAt": "2026-01-21T13:20:00Z",
    },
    {
      "ngoId": "NGO305",
      "itemName": "Winter Hats and Gloves",
      "type": "Clothing",
      "quantityRequested": 80,
      "image": "assets/dummy_assets/requests/Winter Hats and Gloves.jpeg",
      "description": "Warm hats and gloves for elderly citizens.",
      "location": "Hawassa",
      "createdAt": "2026-01-21T14:00:00Z",
    },
    {
      "ngoId": "NGO306",
      "itemName": "First Aid Kits",
      "type": "Health",
      "quantityRequested": 30,
      "image": "assets/dummy_assets/requests/First Aid Kits.jpeg",
      "description": "Complete first aid kits for local clinics.",
      "location": "Adama",
      "createdAt": "2026-01-21T15:10:00Z",
    },
  ];
}
